import Head from "next/head";
import Commissions from "./index/Commissions";
import Hero from "./index/Hero";
import NewArrivals from "./index/NewArrivals";
import Newsletter from "./index/Newsletter";
import data from "../data/data";

export default function Home() {
  const { hero, commissions, newArrivals, newsletter, products } = data;
  return (
    <div className="w-full h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero hero={hero} />
      <div className="flex flex-col items-center px-4 md:px-28">
        <NewArrivals newArrivals={newArrivals} products={products} />
        <Commissions commissions={commissions} />
        <Newsletter newsletter={newsletter} />
      </div>
    </div>
  );
}
